---
title: "TallestBuildingsAssignment"
author: "Daniel Bies and Gonzalo Del Carpio"
date: "October 3, 2017"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
tb=read_excel("tallestbuildings.xlsx")
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
names(tb)[6]="height"
```

```{r}
head(tb)
```

```{r}
Citycounts=tb%>%group_by(City)%>%summarize(number=length(height))
```


###Code for graph 1:

```{r}
ggplot(Citycounts,aes(reorder(City,-number),number)) + geom_bar(stat= "identity", fill="red") + coord_flip()
```

###Code for graph 2:

```{r}
Citymean=tb%>% group_by(City)%>%summarise(length=mean(height))
ggplot(Citymean,aes(reorder(City,-length),length)) + geom_bar(stat= "identity", fill="blue") + coord_flip()
```

```{r}
#install.packages("countrycode")
library(countrycode)
```

```{r}
tb=separate(tb, City, into = c("City", "Country"), sep = -5)
```

```{r}
tb$Country=gsub("[()]","", tb$Country)
```

```{r}
tb$Country = countrycode(tb$Country,"iso2c","country.name")
```

###Code for Graph 3:

```{r}
Countrycounts=tb%>%group_by(Country)%>%summarize(number=length(height))
ggplot(Countrycounts,aes(reorder(Country,-number),number)) + geom_bar(stat= "identity", fill="red") + coord_flip()
```

###Code for Graph 4:

```{r}
Countrymean=tb%>% group_by(Country)%>%summarise(length=mean(height))
ggplot(Countrymean,aes(reorder(Country,-length),length)) + geom_bar(stat= "identity", fill="blue") + coord_flip()
```

###Code for Graph 5: 

```{r}
Colorcount= tb%>% group_by(Country)%>%summarize(TotalBuildings = n(), MeanHeight = mean(height))
```

```{r}
ggplot(Colorcount, aes(reorder(Country,-MeanHeight),MeanHeight, fill = as.factor(TotalBuildings))) + geom_bar(stat= "identity", position = "dodge") + coord_flip()
```

###Code for Graph 6:

```{r}
BuildUse= tb%>%group_by(Use)%>%summarize(MeanHeight=mean(height))
```

```{r}
ggplot(BuildUse, aes(reorder(Use,-MeanHeight), MeanHeight)) + geom_bar(stat = "identity", position = "dodge", fill="blue") + coord_flip()
```

